name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      # Now that python 3.6 and 3.8 are EOL, we should remove them from the test matrix.
      # Perhaps we no longer need to test python 3.6 and 3.8, it's up to you.
      # - uses: actions/checkout@v3
      # - name: Set up Python 3.6 (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.6"
      # - name: Set up Python 3.6 (Ubuntu)
      #   if: matrix.platform == 'ubuntu-22.04'
      #   run: |
      #     sudo add-apt-repository ppa:deadsnakes/ppa
      #     sudo apt-get update
      #     sudo apt-get install -y python3.6
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.8"
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Test with tox
        run: python -m tox
